version: '3.1'

services:
    postgres:
        image: postgres
        network_mode: host
        environment:
            POSTGRES_PASSWORD: postgres

    contacts-backend-service:
        build: ./contacts-backend-service
        network_mode: host
        depends_on:
            - postgres

    contacts-frontend-service:
        build: ./contacts-frontend-service
        network_mode: host
        depends_on:
            - contacts-backend-service
