version: '3.1'

services:
  postgres:
    image: postgres
    network_mode: host
    environment:
      POSTGRES_PASSWORD: postgres

  contacts-caching-service:
    build:
      context: ./contacts-caching-service
      args:
        server_port: 8080
    network_mode: host
    depends_on:
      - contacts-persistence-service
    command: java -jar /opt/contacts-caching-service.jar --spring.profiles.active=dev

  contacts-persistence-service:
    build:
      context: ./contacts-persistence-service
      args:
        server_port: 8081
    network_mode: host
    depends_on:
      - postgres
    command: java -jar /opt/contacts-persistence-service.jar --spring.profiles.active=dev,postgres-dev
