version: '3.1'

services:
  postgres:
    image: postgres
    network_mode: host
    environment:
      POSTGRES_PASSWORD: postgres

  contacts-frontend-service:
    build:
      context: ./contacts-frontend-service
      args:
        server_port: 8080
    network_mode: host
    depends_on:
      - contacts-backend-service
    command: java -jar /opt/contacts-frontend-service.jar --spring.profiles.active=dev

  contacts-backend-service:
    build:
      context: ./contacts-backend-service
      args:
        server_port: 8081
    network_mode: host
    depends_on:
      - postgres
    command: java -jar /opt/contacts-backend-service.jar --spring.profiles.active=dev,postgres-dev
